"""RAG Pipeline domain models.

All models inherit from ``VindictaModel`` (Constitution §II).
Used by the scraper, storage, and MCP server modules.
"""

from __future__ import annotations

import hashlib
from datetime import datetime, timezone

from pydantic import AnyUrl, Field, field_validator

from vindicta_foundation.models.base import VindictaModel


class RulesSegment(VindictaModel):
    """A chunked segment of rules text scraped from a target site.

    Represents a single unit of knowledge stored in ChromaDB
    with its embedding vector and versioning metadata (FR-003, FR-004).
    """

    url: AnyUrl = Field(..., description="Source URL of the rule")
    content_markdown: str = Field(
        ..., description="Cleaned, markdown-formatted rule text"
    )
    content_hash: str = Field(
        ...,
        description="SHA-256 hash of content_markdown for dedup (FR-003)",
    )
    version: int = Field(
        default=1,
        ge=1,
        description="Version counter for url+content tracking (FR-006)",
    )
    embedding: list[float] = Field(
        default_factory=list,
        description="Vector embedding generated by Ollama",
    )
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Time of ingestion",
    )

    @field_validator("content_markdown")
    @classmethod
    def validate_content_not_empty(cls, v: str) -> str:
        """Content must not be empty."""
        if not v.strip():
            raise ValueError("content_markdown must not be empty")
        return v

    @field_validator("content_hash")
    @classmethod
    def validate_hash_format(cls, v: str) -> str:
        """Content hash must be a valid SHA-256 hex string."""
        if len(v) != 64:
            raise ValueError(f"content_hash must be 64 hex characters, got {len(v)}")
        try:
            int(v, 16)
        except ValueError:
            raise ValueError("content_hash must be a valid hex string")
        return v

    @staticmethod
    def compute_hash(content: str) -> str:
        """Compute SHA-256 hash of content for deduplication."""
        return hashlib.sha256(content.encode("utf-8")).hexdigest()


class AgentQuery(VindictaModel):
    """A query request from an agent to the RAG MCP Server.

    Represents a natural language search passed to ``search_40k_rules``.
    """

    query_text: str = Field(..., description="Natural language search query")
    agent_id: str = Field(
        default="unknown", description="Identifier of the calling agent"
    )
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Time of query",
    )

    @field_validator("query_text")
    @classmethod
    def validate_query_length(cls, v: str) -> str:
        """Query must be 4-4096 characters to prevent abuse."""
        if len(v) < 4:
            raise ValueError(f"query_text must be >= 4 characters, got {len(v)}")
        if len(v) > 4096:
            raise ValueError(f"query_text must be <= 4096 characters, got {len(v)}")
        return v
